<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Psr\\Container\\ContainerInterface' => 'get1',
  'Nazca\\Managers\\Endpoints\\EndpointInvocatorInterface' => 'get2',
  'Nazca\\Managers\\Http\\HttpRequestManagerInterface' => 'get3',
  'Nazca\\Managers\\Endpoints\\EndpointInvocator' => 'get4',
  'subEntry1' => 'get5',
  'Nazca\\Managers\\Http\\HttpRequestManager' => 'get6',
  'subEntry2' => 'get7',
  'subEntry3' => 'get8',
  'Nazca\\Managers\\Routes\\RouteManager' => 'get9',
  'subEntry4' => 'get10',
  'Nazca\\Validators\\RouteValidator' => 'get11',
  'subEntry5' => 'get12',
  'Symfony\\Component\\HttpFoundation\\Request' => 'get13',
);

    protected function get1()
    {
        return 'DI\\Container';
    }

    protected function get2()
    {
        return $this->delegateContainer->get('Nazca\\Managers\\Endpoints\\EndpointInvocator');
    }

    protected function get3()
    {
        return $this->delegateContainer->get('Nazca\\Managers\\Http\\HttpRequestManager');
    }

    protected function get5()
    {
        return $this->delegateContainer->get('Nazca\\Managers\\Routes\\RouteManager');
    }

    protected function get4()
    {
        $object = new Nazca\Managers\Endpoints\EndpointInvocator($this->get5());
        return $object;
    }

    protected function get7()
    {
        return $this->delegateContainer->get('Psr\\Container\\ContainerInterface');
    }

    protected function get8()
    {
        return $this->delegateContainer->get('Nazca\\Managers\\Endpoints\\EndpointInvocatorInterface');
    }

    protected function get6()
    {
        $object = new Nazca\Managers\Http\HttpRequestManager($this->get7(), $this->get8());
        return $object;
    }

    protected function get10()
    {
        return $this->delegateContainer->get('Nazca\\Validators\\RouteValidator');
    }

    protected function get9()
    {
        $object = new Nazca\Managers\Routes\RouteManager($this->get10());
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('Symfony\\Component\\HttpFoundation\\Request');
    }

    protected function get11()
    {
        $object = new Nazca\Validators\RouteValidator($this->get12());
        return $object;
    }

    protected function get13()
    {
        $object = new Symfony\Component\HttpFoundation\Request([
        ], [
        ], [
        ], [
        ], [
        ], [
        ], NULL);
        return $object;
    }

}
